# 生命周期函数执行
> vue2中的生命周期函数执行是通过`callHook`方法执行
```js
export function callHook (vm: Component, hook: string) {
  pushTarget()
  const handlers = vm.$options[hook]
  const info = `${hook} hook`
  if (handlers) {
    for (let i = 0, j = handlers.length; i < j; i++) {
      invokeWithErrorHandling(handlers[i], vm, null, vm, info)
    }
  }
  if (vm._hasHookEvent) {
    vm.$emit('hook:' + hook)
  }
  popTarget()
}
```
handlers是实例中的hook函数，若handlers存在便遍历handlers数组，并执行`invokeWithErrorHandling`，在某情况下，例如使用`Vue.component()`创建实例的时候会有可能使得handler数组长度大于1，目前暂不探讨该部分。
接下来我们来到`invokeWithErrorHandling`函数中，可以看到其实该函数的实现比较通俗易懂，执行传入的handler函数，并且保存结果，随后根据是否为promise类型进行错误处理
```js
export function invokeWithErrorHandling (
  handler: Function,
  context: any,
  args: null | any[],
  vm: any,
  info: string
) {
  let res
  try {
    // 有args就使用apply，否则使用call
    res = args ? handler.apply(context, args) : handler.call(context)
    if (isPromise(res)) {
      res.catch(e => handleError(e, vm, info + ` (Promise/async)`))
    }
  } catch (e) {
    handleError(e, vm, info)
  }
  return res
}
```
可以看到其中有一个判断`isPromise`，我们找到该方法，可以发现只做了三个判断，第一个`isDef`判断是否为定义过的变量，后续为判断是否有then catch等方法。
```js
export function isPromise (val: any): boolean {
  return (
    isDef(val) &&
    typeof val.then === 'function' &&
    typeof val.catch === 'function'
  )
}
```
至于为什么不使用`instanceof`来判断promise类型，是因为`instanceof`只能判断由promise构造函数生成的实例，而若使用环境下用了第三方的Promise库，则该方法的判断只有一个否定结果，因此使用自定义的判断方法能避免此类问题